### ISSUE TITLE
Certain Node.js packages missing from Linux build

### ISSUE THREAD

**Issue by TaiAurori** [deltamodders/deltamod#72]
Whenever I download and launch Deltamod 2.0.5 in any form on my Arch system, I get a white window with the following error in the terminal:
```
UnhandledPromiseRejectionWarning: Error: Cannot find module 'express'
Require stack:
- (...)/deltamod/resources/app/node/GameBanana.js
- (...)/deltamod/resources/app/node/IPCHandlers.js
- (...)/deltamod/resources/app/node/Runner.js
```

I managed to get it working by downloading `Deltamod 2.0.5 - Linux - Unpackaged files` from the Itch mirror and running `npm i` in `resources/app` before launching.

**Comment by fnr1r** [comment]
Can you try the `2.1.0` release?

**Comment by TaiAurori** [comment]
Launches as expected now. The AppImage release still fails to patch the game due to #62, but the non-AppImage release works fine.
